[0m20:36:11.752776 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4CC42D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4CC3CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4CC3150>]}


============================== 20:36:11.752776 | 80b48c77-4a6b-4f27-aaf4-a45dfd289eda ==============================
[0m20:36:11.752776 [info ] [MainThread]: Running with dbt=1.9.3
[0m20:36:11.752776 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\awadi\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt compile --models stg_binomes stg_benevoles stg_jeunes', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:36:11.752776 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\awadi\Downloads\article1-data-pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:36:11.752776 [debug] [MainThread]: Command `dbt compile` failed at 20:36:11.752776 after 0.10 seconds
[0m20:36:11.752776 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4C62690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4CC3150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276E4CC2590>]}
[0m20:36:11.752776 [debug] [MainThread]: Flushing usage events
[0m20:36:12.158386 [debug] [MainThread]: An error was encountered while trying to flush usage events
